id: PA97D9E99
initial_creation_type: input
source_metadata:
  title: Fifth Dodrupchen Rinpoche Series
  language: en
  description: 'Texts by and about the Fifth Dodrupchen Rinpoche, Jigme Long-yang
    (''jigs med klong yangs, b. 1962):'
  volume:
    14f9a406196d4226a42bdd9798364351:
      title: Prayer for Swift Rebirth of the Fourth Dodrupchen Rinpoche, Tupten Trinlé
        Palzangpo
      parent: Swift Rebirth Prayers
created_at: '2022-02-28T23:14:32.337770'
last_modified_at: '2022-02-28T23:14:32.337776'
